/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_xiaym_fcitx5_Fcitx5 */

#ifndef _Included_cn_xiaym_fcitx5_Fcitx5
#define _Included_cn_xiaym_fcitx5_Fcitx5
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_xiaym_fcitx5_Fcitx5
 * Method:    findWindow
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaym_fcitx5_Fcitx5_findWindow
  (JNIEnv *, jclass);

/*
 * Class:     cn_xiaym_fcitx5_Fcitx5
 * Method:    userTyping
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaym_fcitx5_Fcitx5_userTyping
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
