/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_xiaym_fcitx5_Fcitx5Wayland */

#ifndef _Included_cn_xiaym_fcitx5_Fcitx5Wayland
#define _Included_cn_xiaym_fcitx5_Fcitx5Wayland
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_xiaym_fcitx5_Fcitx5Wayland
 * Method:    initialize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cn_xiaym_fcitx5_Fcitx5Wayland_initialize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cn_xiaym_fcitx5_Fcitx5Wayland
 * Method:    updateWindow
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_cn_xiaym_fcitx5_Fcitx5Wayland_updateWindow
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
